### ISSUE TITLE
Could not find 'invesdwin-context-python-runtime-python4j' dependency in your maven repository

### ISSUE THREAD

**Issue by Gou123456** [invesdwin/invesdwin-scripting#5]
Releases and snapshots are deployed to this maven repository:
https://invesdwin.de/repo/invesdwin-oss-remote/

I could not find  'invesdwin-context-python-runtime-python4j'  jar in your  maven repository.  and I find in 
https://mvnrepository.com/,  It prompts me to find  https://maven.scijava.org/content/repositories/public/ , but too.

![image](https://user-images.githubusercontent.com/40093535/227128815-ac6f19d5-568a-46fb-a7e7-ddf64eaa1d21.png)

so , could  you tell me why didn't upload this jar？ and can upload it later ？ thank you

**Comment by subes** [comment]
You can get it as a snapshot here: https://invesdwin.de/nexus/#browse/browse:invesdwin-oss:de%2Finvesdwin%2Finvesdwin-context-python-runtime-python4j%2F1.0.4-SNAPSHOT

If you need a release version, either rename the current snapshot or create a release yourself (build locally is easiest with invesdwin-oss repo). I did not create an official release for a while, would need to revive the automation for a full release which I am postponing right now.

**Comment by Gou123456** [comment]
thank you
